export default {
  input: 'src/index.js',
  treeshake: false,
  external: ['fs'],
  output: {
    file: 'dist/index.cjs',
    format: 'cjs',
    exports: 'named',
    intro: '// This file is auto-generated by Rollup',
  },
};
